name: al_analysis
channels:
  # TODO even need conda-forge for python?
  #- conda-forge
  - defaults
dependencies:
  # TODO keep openmp/compiler stuff in here for installing olfsysm?
  # TODO need =<exact-version?> at end?
  - python=3.8.12
  - pip:
    # TODO or specify url (git+https://github.com/ejhonglab/al_analysis)? editable?
    - .
